INSERT INTO Patient (
	pimsPatientIdentifier
	,name
	,gender
	,speciesDescription
	,breedId
	,breedDescription
	,colorId
	,microchipId
	,colorDescription
	,dateOfDeath
	,dateOfBirth
	,spayedOrNeutered
	,inactive
	,weight
	,weightUnit
	,weightUnitDescription
	,rabiesTag
	,clientPimsId
	,pimsClientIdentifier
	,locationId
	,dpUid
	,pimsId
	,siteId
	,agentVersion
	,action
	,dpCreateDate
	,dpModifiedDate
	,syncDate
	,correlationId
	,lastModifiedByCorrelationId
	,generation
	,deleted
	)
VALUES (
	@pimsPatientIdentifier
	,@name
	,@gender
	,@speciesDescription
	,@breedId
	,@breedDescription
	,@colorId
	,@microchipId
	,@colorDescription
	,@dateOfDeath
	,@dateOfBirth
	,@spayedOrNeutered
	,@inactive
	,@weight
	,@weightUnit
	,@weightUnitDescription
	,@rabiesTag
	,@clientPimsId
	,@pimsClientIdentifier
	,@locationId
	,@dpUid
	,@pimsId
	,@siteId
	,@agentVersion
	,@action
	,@dpCreateDate
	,@dpModifiedDate
	,@syncDate
	,@correlationId
	,@lastModifiedByCorrelationId
	,@generation
	,@deleted
	)